:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]
:IHookEvents: pass:normal[xref:interfaces.adoc#IHookEvents[`IHookEvents`]]
:xref-IHookEvents-HookSwap-bytes32-address-int128-int128-uint128-uint128-: xref:interfaces.adoc#IHookEvents-HookSwap-bytes32-address-int128-int128-uint128-uint128-
:xref-IHookEvents-HookFee-bytes32-address-uint128-uint128-: xref:interfaces.adoc#IHookEvents-HookFee-bytes32-address-uint128-uint128-
:xref-IHookEvents-HookModifyLiquidity-bytes32-address-int128-int128-: xref:interfaces.adoc#IHookEvents-HookModifyLiquidity-bytes32-address-int128-int128-
:xref-IHookEvents-HookBonus-bytes32-uint128-uint128-: xref:interfaces.adoc#IHookEvents-HookBonus-bytes32-uint128-uint128-
= Interfaces

[.readme-notice]
NOTE: This document is better viewed on the docs page.

Interfaces to be used by Hooks 

 * {IHookEvents}: Interface for standard hook events emission.

== Interfaces

:HookSwap: pass:normal[xref:#IHookEvents-HookSwap-bytes32-address-int128-int128-uint128-uint128-[`++HookSwap++`]]
:HookFee: pass:normal[xref:#IHookEvents-HookFee-bytes32-address-uint128-uint128-[`++HookFee++`]]
:HookModifyLiquidity: pass:normal[xref:#IHookEvents-HookModifyLiquidity-bytes32-address-int128-int128-[`++HookModifyLiquidity++`]]
:HookBonus: pass:normal[xref:#IHookEvents-HookBonus-bytes32-uint128-uint128-[`++HookBonus++`]]

[.contract]
[[IHookEvents]]
=== `++IHookEvents++` link:https://github.com/OpenZeppelin/uniswap-hooks/blob/master/src/interfaces/IHookEvents.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import "uniswap-hooks/src/interfaces/IHookEvents.sol";
```

Interface for standard hook events emission.

NOTE: Hooks should inherit from this interface to standardized event emission.

[.contract-index]
.Events
--
* {xref-IHookEvents-HookSwap-bytes32-address-int128-int128-uint128-uint128-}[`++HookSwap(poolId, sender, amount0, amount1, hookLPfeeAmount0, hookLPfeeAmount1)++`]
* {xref-IHookEvents-HookFee-bytes32-address-uint128-uint128-}[`++HookFee(poolId, sender, feeAmount0, feeAmount1)++`]
* {xref-IHookEvents-HookModifyLiquidity-bytes32-address-int128-int128-}[`++HookModifyLiquidity(poolId, sender, amount0, amount1)++`]
* {xref-IHookEvents-HookBonus-bytes32-uint128-uint128-}[`++HookBonus(poolId, amount0, amount1)++`]

--

[.contract-item]
[[IHookEvents-HookSwap-bytes32-address-int128-int128-uint128-uint128-]]
==== `[.contract-item-name]#++HookSwap++#++(bytes32 indexed poolId, address indexed sender, int128 amount0, int128 amount1, uint128 hookLPfeeAmount0, uint128 hookLPfeeAmount1)++` [.item-kind]#event#

Emitted when a hook executes a swap outside of Uniswap's default concentrated liquidity AMM in a pool
identified by `poolId`, being `sender` the initiator of the swap, `amount0` and `amount1` the swap amounts
(positive for input, negative for output), and `hookLPfeeAmount0`, `hookLPfeeAmount1` the LP fees.

[.contract-item]
[[IHookEvents-HookFee-bytes32-address-uint128-uint128-]]
==== `[.contract-item-name]#++HookFee++#++(bytes32 indexed poolId, address indexed sender, uint128 feeAmount0, uint128 feeAmount1)++` [.item-kind]#event#

Emitted when a hook charges fees in a pool identified by `poolId`, being `sender` the initiator of the swap or
the liquidity modifier, `feeAmount0` and `feeAmount1` the fees charged in currency0 and currency1, defined by the `poolId`.

[.contract-item]
[[IHookEvents-HookModifyLiquidity-bytes32-address-int128-int128-]]
==== `[.contract-item-name]#++HookModifyLiquidity++#++(bytes32 indexed poolId, address indexed sender, int128 amount0, int128 amount1)++` [.item-kind]#event#

Emitted when a liquidity modification is executed in a pool identified by `poolId`, being `sender` the liquidity modifier,
`amount0` and `amount1` the amounts added or removed in currency0 and currency1, defined by the `poolId`.

[.contract-item]
[[IHookEvents-HookBonus-bytes32-uint128-uint128-]]
==== `[.contract-item-name]#++HookBonus++#++(bytes32 indexed poolId, uint128 amount0, uint128 amount1)++` [.item-kind]#event#

Emitted when a bonus is added to an operation in a pool identified by `poolId`, being `amount0` and `amount1` the amounts
added in currency0 and currency1, defined by the `poolId`.

